### PR TITLE
Change "it's" to "its" in README

### PR DESCRIPTION
**Pull request by gerrymiller**
Small spelling error, please review and approve, @thomas-zinn

### CODE REVIEW

**Comment by sween** [comment]
Yeah, I dunno... "it's" is a proper contraction.

**Comment by gerrymiller** [comment]
In this case, @sween, the possessive form was used, but mistakenly misspelled as a contraction. Common error!

**Comment by gerrymiller** [comment]
@thomas-zinn are you going to approve this PR?

**Comment by thomas-zinn** [comment]
I never received any notifications that this was pending action from me.

**Comment by gerrymiller** [comment]
Weird.

**Pull request merged**
